Fe rest
fragjulian/ASE-WS22-MazeRunner pull request #53
Opened 2022-12-29 16:57 UTC by Kristinaliebhart

Color picker and text boxes for rgb values implemented; Unit tests added

2022-12-29 17:47 UTC, fragjulian requested changes
LGTM, good test coverage! Please, have a look at my other comments.

Ideally, include a few screenshots or GIFs of the UI changes to your PRs.

In the future, please keep the changeset smaller and rebase regularly onto latest main to avoid merge conflicts.

2022-12-29 17:47 UTC, fragjulian commented on frontend/src/app/app.component.ts
> +    console.log(event);
I think this should not be in `app.component`. Looks like a leftover?

2022-12-29 17:47 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.ts
> +    this.httpClient.post('http://localhost:8080/api/maze/colorwalldetector/realdistanceheuristic/depthfirst', transformedImage, {
I think the port is now `8081` for both local and deployed server.

2022-12-29 17:47 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.ts
> +    this.httpClient.post('http://localhost:8080/api/maze/colorwalldetector/realdistanceheuristic/depthfirst', transformedImage, {
Usually, there is a dedicated service for the REST communication. Can also be done in a follow-up PR.

2022-12-30 16:53 UTC, Poetzi commented
Requested changes should be adressed now

2022-12-31 08:28 UTC, fragjulian requested changes

2022-12-31 08:28 UTC, fragjulian commented on selenium/src/test/java/at/stulpinger/ase/UITest.java
> +    assertThat(solveMazeButton.isEnabled()).isTrue();
I think the correct behavior is still that the button is disabled as long there is no image uploaded. Please fix this in the code instead of adapting the UI test.

2022-12-31 08:28 UTC, fragjulian commented on selenium/src/test/java/at/stulpinger/ase/UITest.java
> +    assertThat(solveMazeButton.getText()).isEqualTo("");
Please verify the button's content ("Upload Image") in another way if it does not work this way.
e.g. use `.getAttribute("value")` instead.

2022-12-31 09:32 UTC, fragjulian commented
Also, I noticed that there are some issues with displaying the result image:
![image](https://user-images.githubusercontent.com/20352438/210131863-35342a74-b4e2-44bc-ab28-728ed28e0e57.png)

Please fix this before merging to main.

Also, I have some concerns about the color picker. But this component is still under development, right?

2023-01-01 20:28 UTC, fragjulian approved these changes

2023-01-01 20:29 UTC, merged