Fe optimization
fragjulian/ASE-WS22-MazeRunner pull request #58
Opened 2023-01-02 17:48 UTC by Poetzi

Did a lot of code quality steps.

2023-01-02 18:50 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.spec.ts
> +  it('should have a canvas element', () => {
nice test coverage!

2023-01-02 21:53 UTC, fragjulian requested changes

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/colorpicker/colorpicker.component.ts
> +  canvas: any;
It is generally discouraged to use the type `any` in TypeScript as it circumvents the whole idea of the language. Please use a proper type or introduce a new one, if necessary.

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/colorpicker/colorpicker.component.ts
> +    const dColor = dataArray[2] + 256 * dataArray[1] + 65536 * dataArray[0];
Instead of explaining the property assignments, you could add a comment here that explains what is actually happening in this line, i.e. what is the `dColor` and how is it calculated?

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.html
> +    <!-- This element is hidden and only used to store the selected color -->
it is also used to pick the color. it is just triggered via another button

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +  // Flag to track if the user is currently drawing on the canvas
yes, but what does the flag _actually_ indicate? 
→ the user is drawing as long as they have the primary mouse button pressed

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +  // Event handler for the mousedown event on the canvas
such comments are still redundant IMO
does not apply to all comments → as discussed in person

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +    // Get the width and height of the canvas
example of a comment that is redundant IMO as it does not give any additional information

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +    // Clear the canvas using the clearRect method of the canvas context
[example]
`Clear the canvas` would be enough here as anyone that understands TS code can see that the clearRect method of the canvas context is called to achieve this → does not have to be mentioned again

2023-01-02 21:53 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.ts
> +  rgbvalueobstacle = '219,219,219';
here, a comment would actually be helpful that explains what the value `219,219,219` means and why it is the default

2023-01-02 21:58 UTC, fragjulian commented
Please, improve the design of the buttons a bit (e.g. use the `btn` class as in the builder component). Also, the title of the result image is a bit too technical IMO. Better would be e.g. "Solved Maze".
![image](https://user-images.githubusercontent.com/20352438/210280532-db152196-9785-46ec-8a6f-2ba173515bb9.png)

2023-01-03 09:05 UTC, Poetzi commented
![maze upload with check](https://user-images.githubusercontent.com/49530417/210327101-025e53d8-4787-4956-9045-de9ac00cb1c0.gif)

2023-01-05 11:01 UTC, fragjulian requested changes

2023-01-05 11:01 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.ts
> +          if (colorSet.size > 2000) {
please add a comment that explains the magic value `2000`

2023-01-05 11:01 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.ts
> +  checkImage(image: File): Observable<boolean> {
[idea] this functionality might fit into a separate service

2023-01-05 11:02 UTC, fragjulian commented
please have a look at my comments - rest LGTM! 
please do not add functionality to an open PR in the future → close the PR or open another one instead.

2023-01-16 18:15 UTC, fragjulian approved these changes

2023-01-16 18:15 UTC, fragjulian commented on frontend/src/app/app.module.ts
> +    ToastrModule.forRoot(/*{ timeOut: 5000, enableHtml: true }*/),
leftover?

2023-01-16 18:15 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.html
> +   <!-- <div *ngIf="errorMessage" class="error">{{ errorMessage }}</div> -->
leftover?

2023-01-16 18:20 UTC, merged