Maze solver auto solve
fragjulian/ASE-WS22-MazeRunner pull request #70
Opened 2023-01-07 21:20 UTC by gregorla12

I implemented a maze auto solver in the maze builder. When the user starts to paint the maze will be submitted in json and the solution path will be returned. This path will then be displayed directly in the maze solver. The brush selection works but it requires some optical improvements. 

![grafik](https://user-images.githubusercontent.com/94615170/211170636-90b2c995-9dec-44c1-ba60-affbcb1ebc59.png)

2023-01-08 14:12 UTC, fragjulian requested changes
Really awesome feature so far!

2023-01-08 14:12 UTC, fragjulian commented on backend/src/main/java/com/example/mazerunner/SquareDistance.java
> +            recursiveResult.addAll(getNeighbouringPixels(resultPosition, radius - 1, width, height).stream().filter(p -> !recursiveResult.contains(p) && !p.equals(position)).toList());
please add some line breaks for better readability

2023-01-08 14:12 UTC, fragjulian commented on backend/src/test/java/com/example/mazerunner/EdgeDetectionWallDetectionTest.java
> +public class EdgeDetectionWallDetectionTest {
please don't forget to add unit tests

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.html
> +      <input (click)="saveBrushColor()" [(ngModel)]="selectedBrush" id="wall" name="paintingType" type="radio"
To follow the existing style, you can use Bootstrap's radio buttons:
https://getbootstrap.com/docs/5.0/forms/checks-radios/#radios

Alternatively, radio button groups might also be an option here:
https://getbootstrap.com/docs/5.0/components/button-group/#checkbox-and-radio-button-groups

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +class Position {
you could extract this class into a separate file

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +  selectedBrush = "wall"
[idea] introduce an enum for the possible values/options

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +  private brushColors = this.initialBrushColors;
[idea] create a class with three fields instead of using an array with three entries for better comprehensibility

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +  postResponse: any;
please avoid using `any`

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +    this.httpClient.post(`http://localhost:8081/api/maze/path?sizeX=${this.canvas!.width / this.pixelSize}&sizeY=${this.canvas!.height / this.pixelSize}`, returnObject, {
please create a service that executes the rest request

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +            for (let path of this.postResponse.body.path) {
extract this (draw solved path) into a method

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +  private setHasPosition(set: Set<Position>, position: Position): boolean {
poor method name, IMO
can be understood as a setter method

2023-01-08 14:12 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +    this.saveBrushColor()
[might be out of scope of this issue]
what about some debounce time? if the user clicks very fast on the canvas, many REST requests are executed - this puts unnecessary load on the server

→ e.g. only allow re-drawing every X ms (e.g. only once a second)

2023-01-08 14:28 UTC, fragjulian commented
I played with the builder a bit and noticed that the path goes through such walls:
![image](https://user-images.githubusercontent.com/20352438/211201675-2552f42b-4086-4ef5-8b48-d8dc810abc60.png)

Is this expected behavior?

Also, please don't forget to add color configs for start and end position

2023-01-08 14:31 UTC, fragjulian commented
Also I managed to get an out of bound exception:
```
java.lang.ArrayIndexOutOfBoundsException: Index 40 out of bounds for length 40
	at com.example.mazerunner.JsonWallDetector.detectWall(JsonWallDetector.java:42)
```

2023-01-08 14:32 UTC, fragjulian commented
Also, the border is being ignored apparently:

![image](https://user-images.githubusercontent.com/20352438/211201964-0df8505e-7823-432a-ba67-81ecade2848a.png)

[Minor] Adding the border should also re-trigger the solution path.

2023-01-08 15:46 UTC, gregorla12 commented on backend/src/main/java/com/example/mazerunner/JsonWallDetector.java
> +public class JsonWallDetector implements WallDetector {
ColorWallDetector uses a buffered image and detects walls if they have a spesific color. The JsonWallDetector gets a list of Positions for obstacles and walls via its setters by spring. The methods appear as unused in the ide, however spring uses them. Walls and obstacles are then detected based on this input lists. I do not think it is a good idea to use only one class. 
I will add JavaDoc to clarify this and think about a better name for the class.

2023-01-08 15:47 UTC, gregorla12 commented on backend/src/main/java/com/example/mazerunner/Maze.java
> +        goal = new Position(sizeX - 5, sizeY - 5);
I do not want to create a constant for this magic value. Reason: These are dummy values and in the final version the goal should be detected automatically. @florianlan is working on this.

2023-01-08 15:48 UTC, gregorla12 commented
Hi, thanks for the detailed review. 
- About the safety distance: The default value is no safety distance. A different value can be set in the request. Maybe we should include an input field somewhere so the user can enter their desired safety distance. 
- Regarding the first path image you mentioned: Yes, this is the intended behaviour in the default distance metric. Diagonal path is allowed even if there is a diagonal wall in the other direction. This is handled by the distance metric (more specifically there is a method getNeighbouringPixels which returns all directly reachable neighbours) which can also be set in the request. The default case is EuclideanDistance. There is a second distance metric available called SquareDistance. This distance metric does not allow such paths. 
- I will look at the IndexOutOfBoundsException you talked about. Yes, changing the border should re-trigger the path. 
I will try to address your feedback until tomorrow before our next meeting.

2023-01-16 18:24 UTC, fragjulian submitted a review, later dismissed

2023-01-16 18:24 UTC, fragjulian commented on backend/src/test/java/com/example/mazerunner/PositionDetectorColorTest.java
> +public class PositionDetectorColorTest {
why is this class empty?

2023-01-16 18:24 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.html
> +                                                                 src="../../assets/obstacle.png" width="20"><span
I find the linebreaks a little bit weird.

2023-01-16 18:24 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +      //this.restoreBrushColor();
leftover?

2023-01-16 18:24 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.html
> +      <label class="btn btn-outline-primary" for="delete"><img alt="bin" height="20" src="../../assets/bin.png"
as discussed: replace this by a rubber icon for better UX

2023-01-16 18:24 UTC, fragjulian commented on frontend/src/app/maze-builder/maze-builder.component.ts
> +    this.drawPixel(this.cursorPosX, this.cursorPosY, this.brushColors[3]);
dupicated code. please extract logic from drawStartAtCurrentMousePosition and drawGoalAtCurrentMousePosition

2023-01-16 19:33 UTC, gregorla12 commented
We had merge conflicts, I tried to fix them. @Poetzi please check if your code is still working. Also, some frontend tests for the maze builder are still failing...

2023-01-16 19:41 UTC, fragjulian submitted a review, later dismissed

2023-01-22 11:05 UTC, fragjulian approved these changes

2023-01-22 11:09 UTC, merged