[Fe] final additions
fragjulian/ASE-WS22-MazeRunner pull request #87
Opened 2023-01-24 10:37 UTC by Kristinaliebhart

2023-01-24 15:13 UTC, fragjulian requested changes

2023-01-24 15:13 UTC, fragjulian commented on frontend/src/app/rest-upload/rest-upload.component.ts
> +      transformedImage.append('endcolor', this.rgbvalueend)
I tried it locally and it did NOT work.
Maybe it is because of this parameter → should be `goalcolor` instead of `endcolor`!

2023-01-25 08:47 UTC, fragjulian commented
@Kristinaliebhart please fix the endpoint parameter as described above and then I can approve your changes. :)

2023-01-25 18:19 UTC, Poetzi commented
@fragjulian Should be good now.  Could you review it again?

2023-01-25 18:22 UTC, Poetzi approved these changes
Looks good to me now!

2023-01-25 18:25 UTC, fragjulian approved these changes

2023-01-25 18:42 UTC, merged